//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSite.AlertResource", typeof(AlertResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        public static string AcademyUpdateSuccessAlert
        {
            get
            {
                return ResourceManager.GetString("AcademyUpdateSuccessAlert", resourceCulture);
            }
        }


        public static string AcceptLawAlert
        {
            get
            {
                return ResourceManager.GetString("AcceptLawAlert", resourceCulture);
            }
        }


        public static string AddNewsSuccessfulAlert
        {
            get
            {
                return ResourceManager.GetString("AddNewsSuccessfulAlert", resourceCulture);
            }
        }


        public static string AdsRenewalSuccessAlert
        {
            get
            {
                return ResourceManager.GetString("AdsRenewalSuccessAlert", resourceCulture);
            }
        }


        public static string AdvertisingRequestSendSuccessfulAlert
        {
            get
            {
                return ResourceManager.GetString("AdvertisingRequestSendSuccessfulAlert", resourceCulture);
            }
        }


        public static string BeginDateBigerEndDateAlert
        {
            get
            {
                return ResourceManager.GetString("BeginDateBigerEndDateAlert", resourceCulture);
            }
        }


        public static string CanNotDeleteAdsWithPaymentAlert
        {
            get
            {
                return ResourceManager.GetString("CanNotDeleteAdsWithPaymentAlert", resourceCulture);
            }
        }


        public static string CommentSentSuccessfulAlert
        {
            get
            {
                return ResourceManager.GetString("CommentSentSuccessfulAlert", resourceCulture);
            }
        }


        public static string DeactiveAccountAlert
        {
            get
            {
                return ResourceManager.GetString("DeactiveAccountAlert", resourceCulture);
            }
        }


        public static string DisposablePasswordIsIncorrectAlert
        {
            get
            {
                return ResourceManager.GetString("DisposablePasswordIsIncorrectAlert", resourceCulture);
            }
        }


        public static string Domain
        {
            get
            {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }


        public static string ExistMobileAlert
        {
            get
            {
                return ResourceManager.GetString("ExistMobileAlert", resourceCulture);
            }
        }


        public static string FailedReCaptchaAlert
        {
            get
            {
                return ResourceManager.GetString("FailedReCaptchaAlert", resourceCulture);
            }
        }


        public static string FailRequestAlert
        {
            get
            {
                return ResourceManager.GetString("FailRequestAlert", resourceCulture);
            }
        }


        public static string LoginRequiredForActionAlert
        {
            get
            {
                return ResourceManager.GetString("LoginRequiredForActionAlert", resourceCulture);
            }
        }


        public static string MessageSentForStylistSuccessfulAlert
        {
            get
            {
                return ResourceManager.GetString("MessageSentForStylistSuccessfulAlert", resourceCulture);
            }
        }


        public static string MessageSentSuccessfulAlert
        {
            get
            {
                return ResourceManager.GetString("MessageSentSuccessfulAlert", resourceCulture);
            }
        }


        public static string MessageSentSuccessfulForAcademyAlert
        {
            get
            {
                return ResourceManager.GetString("MessageSentSuccessfulForAcademyAlert", resourceCulture);
            }
        }


        public static string MessageSentSuccessfulForAdsAlert
        {
            get
            {
                return ResourceManager.GetString("MessageSentSuccessfulForAdsAlert", resourceCulture);
            }
        }


        public static string MessageSentSuccessfulForSalonAlert
        {
            get
            {
                return ResourceManager.GetString("MessageSentSuccessfulForSalonAlert", resourceCulture);
            }
        }


        public static string NeedRequestRenewalSuccessAlert
        {
            get
            {
                return ResourceManager.GetString("NeedRequestRenewalSuccessAlert", resourceCulture);
            }
        }


        public static string NoSelectPhotoAlert
        {
            get
            {
                return ResourceManager.GetString("NoSelectPhotoAlert", resourceCulture);
            }
        }


        public static string NoteSelectManagementAlert
        {
            get
            {
                return ResourceManager.GetString("NoteSelectManagementAlert", resourceCulture);
            }
        }


        public static string NotFoundMobileAlert
        {
            get
            {
                return ResourceManager.GetString("NotFoundMobileAlert", resourceCulture);
            }
        }


        public static string NotPossibleSalonAndStylistAllocateToCustomerAlert
        {
            get
            {
                return ResourceManager.GetString("NotPossibleSalonAndStylistAllocateToCustomerAlert", resourceCulture);
            }
        }


        public static string NotResponseGateWay
        {
            get
            {
                return ResourceManager.GetString("NotResponseGateWay", resourceCulture);
            }
        }


        public static string NotSelectAcademyAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectAcademyAlert", resourceCulture);
            }
        }


        public static string NotSelectAddressAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectAddressAlert", resourceCulture);
            }
        }


        public static string NotSelectAdvertisingAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectAdvertisingAlert", resourceCulture);
            }
        }


        public static string NotSelectCityAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectCityAlert", resourceCulture);
            }
        }


        public static string NotSelectedCourseTypeAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedCourseTypeAlert", resourceCulture);
            }
        }


        public static string NotSelectedDateAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedDateAlert", resourceCulture);
            }
        }


        public static string NotSelectedGroupAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedGroupAlert", resourceCulture);
            }
        }


        public static string NotSelectedSectionAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedSectionAlert", resourceCulture);
            }
        }


        public static string NotSelectGenderAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectGenderAlert", resourceCulture);
            }
        }


        public static string NotSelectPhotoAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectPhotoAlert", resourceCulture);
            }
        }


        public static string NotSelectProvinceAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectProvinceAlert", resourceCulture);
            }
        }


        public static string NotSelectSalonAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectSalonAlert", resourceCulture);
            }
        }


        public static string NotSelectSalonOrStylistForCustomerAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectSalonOrStylistForCustomerAlert", resourceCulture);
            }
        }


        public static string NotSelectServiceAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectServiceAlert", resourceCulture);
            }
        }


        public static string NotSelectSpecialFeeAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectSpecialFeeAlert", resourceCulture);
            }
        }


        public static string NotSelectStylistAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectStylistAlert", resourceCulture);
            }
        }


        public static string NotSelectVideoAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectVideoAlert", resourceCulture);
            }
        }


        public static string NotValidAdsExpireDate3DayAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidAdsExpireDate3DayAlert", resourceCulture);
            }
        }


        public static string NotValidDateAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidDateAlert", resourceCulture);
            }
        }


        public static string NotValidFileFormatAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidFileFormatAlert", resourceCulture);
            }
        }


        public static string NotValidNeedRequestExpireDate3DayAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidNeedRequestExpireDate3DayAlert", resourceCulture);
            }
        }


        public static string NotValidPermissionAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidPermissionAlert", resourceCulture);
            }
        }


        public static string NotValidPhotoAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidPhotoAlert", resourceCulture);
            }
        }


        public static string NotValidPhotoFormatAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidPhotoFormatAlert", resourceCulture);
            }
        }


        public static string NotValidPhotoSizeAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidPhotoSizeAlert", resourceCulture);
            }
        }


        public static string NotValidVideoFormatAlert
        {
            get
            {
                return ResourceManager.GetString("NotValidVideoFormatAlert", resourceCulture);
            }
        }


        public static string OldPasswordIncorrectAlert
        {
            get
            {
                return ResourceManager.GetString("OldPasswordIncorrectAlert", resourceCulture);
            }
        }


        public static string PasswordIsIncorrectAlert
        {
            get
            {
                return ResourceManager.GetString("PasswordIsIncorrectAlert", resourceCulture);
            }
        }


        public static string PaymentSuccesful
        {
            get
            {
                return ResourceManager.GetString("PaymentSuccesful", resourceCulture);
            }
        }


        public static string SalonNotSelectAlert
        {
            get
            {
                return ResourceManager.GetString("SalonNotSelectAlert", resourceCulture);
            }
        }


        public static string SalonUpdateSuccessAlert
        {
            get
            {
                return ResourceManager.GetString("SalonUpdateSuccessAlert", resourceCulture);
            }
        }


        public static string SearchNotResultAlert
        {
            get
            {
                return ResourceManager.GetString("SearchNotResultAlert", resourceCulture);
            }
        }


        public static string StylistProfileIsExistAlert
        {
            get
            {
                return ResourceManager.GetString("StylistProfileIsExistAlert", resourceCulture);
            }
        }


        public static string StylistUpdateSuccessAlert
        {
            get
            {
                return ResourceManager.GetString("StylistUpdateSuccessAlert", resourceCulture);
            }
        }


        public static string StylistUsernameIsExistAlert
        {
            get
            {
                return ResourceManager.GetString("StylistUsernameIsExistAlert", resourceCulture);
            }
        }


        public static string SuccessDeleteAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessDeleteAlert", resourceCulture);
            }
        }


        public static string SuccessLoginAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessLoginAlert", resourceCulture);
            }
        }


        public static string SuccessRegisterAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessRegisterAlert", resourceCulture);
            }
        }


        public static string SuccessRequestAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessRequestAlert", resourceCulture);
            }
        }


        public static string SuccessRequestWithAcceptAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessRequestWithAcceptAlert", resourceCulture);
            }
        }


        public static string SuccessUpdateAlert
        {
            get
            {
                return ResourceManager.GetString("SuccessUpdateAlert", resourceCulture);
            }
        }


        public static string TurnDateExistAlert
        {
            get
            {
                return ResourceManager.GetString("TurnDateExistAlert", resourceCulture);
            }
        }


        public static string UserDontHaveSalonAlert
        {
            get
            {
                return ResourceManager.GetString("UserDontHaveSalonAlert", resourceCulture);
            }
        }


        public static string UserHaveAcademyAlert
        {
            get
            {
                return ResourceManager.GetString("UserHaveAcademyAlert", resourceCulture);
            }
        }


        public static string UserHaveSalonAlert
        {
            get
            {
                return ResourceManager.GetString("UserHaveSalonAlert", resourceCulture);
            }
        }


        public static string UserHaveStylistAlert
        {
            get
            {
                return ResourceManager.GetString("UserHaveStylistAlert", resourceCulture);
            }
        }


        public static string UsernameIsExistAlert
        {
            get
            {
                return ResourceManager.GetString("UsernameIsExistAlert", resourceCulture);
            }
        }


        public static string NotSelectedStoreAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedStoreAlert", resourceCulture);
            }
        }

        public static string NotSelectedJobAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedJobAlert", resourceCulture);
            }
        }

        public static string NotSelectedTypeAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedTypeAlert", resourceCulture);
            }
        }

        public static string NotSelectedArtistAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedArtistAlert", resourceCulture);
            }
        }
        public static string NotSelectedCenterAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedCenterAlert", resourceCulture);
            }
        }
        public static string CanNotDeleteGroupWithChildAlert
        {
            get
            {
                return ResourceManager.GetString("CanNotDeleteGroupWithChildAlert", resourceCulture);
            }
        }

        public static string NotSelectedAlbumAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedAlbumAlert", resourceCulture);
            }
        }
        public static string NotSelectedLanguageAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedLanguageAlert", resourceCulture);
            }
        }
        public static string CanNotDeleteAlert
        {
            get
            {
                return ResourceManager.GetString("CanNotDeleteAlert", resourceCulture);
            }
        }
        public static string NotSelectedCityAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedCityAlert", resourceCulture);
            }
        }
        public static string NotSelectedPeriodAlert
        {
            get
            {
                return ResourceManager.GetString("NotSelectedPeriodAlert", resourceCulture);
            }
        }

        public static string NoPhotoListExistAlert
        {
            get
            {
                return ResourceManager.GetString("NoPhotoListExistAlert", resourceCulture);
            }
        }



    }
}
